### ISSUE TITLE
Problem using sandbox

### ISSUE THREAD

**Issue by seek78** [ionafan2/selling-partner-api-postman-sandbox#1]
> Hi @seek78,
> The error message is self-explanatory: "Credential should be scoped to a valid region, not 'eu-west-1'."
> Make sure you use correct value in `.env` file `AWS_REGION=` or make sure your user/role/permissions set up in correct region in AWS console. They should match. If you need more assistance, open an issue in the sandbox repository.

Hi @ionafan2,
So the IAM user-enabled region on AWS is wrong?
I can't determine how to enable the region on AWS. But aren't IAM users all global?

**Comment by seek78** [comment]
Found the problem, thanks!

**Comment by Bariskau** [comment]
@seek78 what was the problem? i am having the same problem?
